pipeline {
    agent any

    stages{
        stage('Build') {
            steps {
                sh 'echo "am Building the image in the docker"'
            }
        }
        stage('Test') {
            steps {
                sh 'echo "am Testing the image in the docker"'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "am Deploying the image in the doc"'
            }
        }stage('cpudetails'){
            steps{
                '''
                lscpu
                '''
            }
        }
    }
}