pipeline{
    agent any

    stages{
        stage('Build'){
            steps{
                sh 'echo "am building the image in the docker"'
            }
        }
        stage('Test'){
            steps{
                sh 'echo "am testing the image in the docker"'
            }
        }
        stage('Deploy'){
            steps{
                sh 'echo "am Deploying the image in the docker"'
            }
        }
        stage('cpudetails'){
            steps{
                sh '''
                    lscpu
                '''
            }
        }   
            
        
        
    }
}